config/routes.rb
FplGuide::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'  

  resources :blogposts

  resources :teams
  resources :players do
    resources :reviews, skip: [:index, :show]
  end  
  resources :reviews, only: [:destroy]
  resources :matches do
    match 'squad_players/all/edit' => 'squad_players#edit_all', :as => :edit_squad_players, :via => :get
    match 'squad_players/all' => 'squad_players#update_all', :as => :update_squad_players, :via => :put 
    resources :squad_players, only: [:edit, :update, :create, :destroy]
    match 'team_stats/all/edit' => 'team_stats#edit_all', :as => :edit_team_stats, :via => :get 
    match 'team_stats/all' => 'team_stats#update_all', :as => :update_team_stats, :via => :put 
    resources :team_stats, skip: [:index, :show]
  end
  resources :lineups, only: [:create, :destroy]
  
  devise_for :users, skip: [:confirmations, :unlock]

  match 'home',              to: 'static_pages#home', as: :user_root, :via => :get
  match 'help',              to: 'static_pages#help'
  match 'under_development', to: 'static_pages#under_development'  
  match 'dashboard',         to: 'static_pages#dashboard'
  match 'landing',           to: 'subscribers#landing_page'
  root                       to: 'subscribers#landing_page'

  resources :users, only: [:show]
  

  resources :subscribers
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/views/shared/_admin_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <ul class="nav nav-pills nav-stacked">
        <li class="active">
          <%= link_to 'Add Team', new_team_path %>
        </li>
        <li>
          <%= link_to 'Add Player', new_player_path %>
        </li>
        <li>
          <%= link_to 'Add Match', new_match_path %>
        </li>
        <li>
          <%= link_to 'Go to Plans', plans_path %>
        </li>
        <li>
          <%= link_to 'View Subscriptions', subscriptions_path %>
        </li>
        <li>
        <li>
          <a href="http://www.jquery2dotnet.com"><i class="fa fa-cogs fa-fw"></i>Settings</a>
        </li>
      </ul>
    </div>
    <div class="col-md-9">
      <%= render '/shared/userlist' %>
    </div>
  </div>
</div>


	            	            
	            	

app/views/shared/_all_players.html.erb
<div class="col-xs-12 col-md-8 custyle" id="players">
  <table class="table table-striped custab">
		<thead>
    	<tr>
        <th>Name</th>
        <th>Position</th>
        <th>Club</th>
    	</tr>
		</thead>
		<% @players.each do |player| %>
      <tr>
        <td><%= link_to player.name, player %></td>
        <td><%= player.pref_position %></td>
        <td><%= player.team.name %></td>
    	</tr>
		<% end %>
  </table>
	  <div id="infinite-scrolling">
	  	<%= will_paginate @players %>
	  </div>
</div>

app/views/shared/_all_users.html.erb
<h2 id="userlist">All users</h2>

<div class="row">
    <% @users.each do |user| %>
	    <div class="col-md-6 col-lg-6">
	        <div class="media">
	            <a class="pull-left" href="#">
	            	<%= image_tag(user.photo.url(:small), class: "media-object dp img-circle all-users") %>
	            </a>
	            <div class="media-body">
	                <h4 class="media-heading">
	                	<%= user.username %> 
	                	<small><%= link_to "View User", user_path(user) %></small>
	                </h4>
	                <h5>Team: <%= user.fantasy_team_name %> </h5>
	                <hr style="margin:8px auto">

	                <span class="label label-default"></span>
	                <span class="label label-default"></span>
	                <span class="label label-info"></span>
	                <span class="label label-default"></span>
	            </div>
	        </div>

	    </div>	
    <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
		The form contains <%=pluralize(object.errors.count, "error") %>
		</div>
			<ul>
				<% object.errors.full_messages.each do |msg| %>
					<li>* <%= msg %> </li>
				<% end %>
			</ul>
	</div>
<% end %>

app/views/shared/_fantasy_player.html.erb
<li id="<%= fantasy_player.id %>">
	<span class="row">
		<span class="col-md-2">
		    <%= image_tag(fantasy_player.player.photo.url(:small), class: "gravatar") %>			
		</span>
		<span class="col-md-10">
			<span class="player">
				<%= link_to fantasy_player.player.name, fantasy_player.player %>
				| <%= link_to fantasy_player.player.team.name, fantasy_player.player.team.name %>
			</span>
			<span class="content">
				Preferred Position: <%= fantasy_player.player.pref_position %>  |
				Number of Starting Apperances: <%= fantasy_player.player.appearances %>
			</span>
			<span class="timestamp">
				Picked <%= time_ago_in_words(fantasy_player.created_at) %> ago	
			</span>
			<span class="delete">
				<% if current_user == fantasy_player.user %>
					<%= link_to "Remove", fantasy_player, method: :delete, 
						data: { confirm: "You sure?" } %>
				<% end %>
			</span>		
		</span>
			
	</span>
</li>

app/views/shared/_fantasyteam.html.erb
<div class="col-xs-12 col-md-12">
	<% if @fantasy_players.any? %>
		<ol class="microposts">
			<%= render partial: 'shared/fantasy_player', collection: @fantasy_players %>
		</ol>
	<% else %>
		There are no fantasy players picked yet.
	<% end %>
</div>

app/views/shared/_league_table.html.erb
<table class="table" id="match-stats">
    <thead>
        <tr>
            <th></th>
            <th>Points</th>
            <th>Wins</th>
            <th>Draws</th>
            <th>Loses</th>
            <th>Goals For</th>
            <th>Goals Against</th>
            <th>Difference</th>
        </tr>
    </thead>
    <tbody>
    	<% @teams.each do |team| %>
    	<tr>
	    		
	        <td><%= link_to team.name, team_path(team) %></td>
	        <td><%= team.league_points %></td>
	        <td><%= team.won %></td>
	        <td><%= team.drawn %></td>
	        <td><%= team.lost %></td>
	        <td><%= team.goals_for %></td>
	        <td><%= team.goals_against %></td>
            <td><%= team.goal_difference %></td>
      </tr>
      <% end %>
    </tbody>
</table>

app/views/shared/_match_review.html.erb
<div class="col-xs-12 col-md-8 col-md-offset-2 custyle post-match">

  <table class="table table-striped custab">
		<thead>
			<h5 class="text-center"><%= side %> Side</h5> 
    	<tr>
    		<th></th>
        <th>Name</th>
        <th>Starters?</th>
        <th>Minutes</th>
        <th>Scored</th>
        <th>Assisted</th>
        <th>Cautioned?</th>
        <th>Sent-off?</th>
        <th>Rating</th>
    	</tr>
		</thead>
		<% players.each do |player| %>
			<% if player.player.team_id == team %>
				  <tr>
				  	<td><%= link_to "Edit Stats", 
				  			edit_match_squad_player_path(match, player) %></td>
		        <td><%= player.player.name %></td>
		        <td><%= player.starting? %></td>
		        <td><%= player.lasting %></td>
		        <td><%= player.scored %></td>
		        <td><%= player.assisted %></td>
		        <td><%= ("No").html_safe unless player.cautioned? %></td>
		        <td><%= ("No").html_safe unless player.sent_off? %></td>
		        <td><%= player.rating %></td>
	    		</tr>
	    <% end %>
		<% end %>
  </table>

  
</div>

app/views/shared/_matchday_18.html.erb
<div class="col-xs-12 col-md-6 custyle">
  <table class="table table-striped custab">
		<thead>
			<h5 class="text-center"><%= side %> Team: Predicted Squad</h5> 
    	<tr>
        <th>Name</th>
        <th>Position</th>
        <th>Apps</th>
        <th>Goals</th>
        <th>Assists</th>
        <th>Yellow</th>
        <th>Red</th>
    	</tr>
		</thead>
		<% players.each do |player| %>
			<% if called?(player) %>
				  <tr>
		        <td><%= player.name %></td>
		        <td><%= player.pref_position %></td>
		        <td><%= player.appearances %></td>
		        <td><%= player.goals %></td>
		        <td><%= player.assists %></td>
		        <td><%= player.yellow %></td>
		        <td><%= player.red %></td>
	    		</tr>
			<% end %>
		<% end %>
  </table>

</div>

app/views/shared/_team_stats_table.html.erb
<% if match.team_stats.any? %>
    <table class="table" id="match-stats">
        <thead>
            <tr>
                <th><%= home.ticker %></th>
                <th>Stats</th>
                <th><%= away.ticker %></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th><%= home_stat.score unless home_stat.nil? %></th>
                <th class="centerbar">Goals</th>
                <th><%= away_stat.score unless away_stat.nil? %></th>
            </tr>
            <tr>
                
                <th>
                    <% unless home_stat.nil? %>
                        <%= home_stat.shot %>(<%= home_stat.on_target %>)
                    <% end %>
                </th>
                <th class="centerbar">Attempts(on target)</th>
                <th>
                    <% unless away_stat.nil? %>
                        <%= away_stat.shot %>(<%= away_stat.on_target %>)
                    <% end %>                
                </th>
            </tr>
            <tr>
                <th><%= home_stat.offside unless home_stat.nil? %></th>
                <th class="centerbar">Offsides</th>
                <th><%= away_stat.offside unless away_stat.nil? %></th>  
            </tr>
            <tr>
                <th><%= home_stat.foul unless home_stat.nil? %></th>
                <th class="centerbar">Fouls</th>
                <th><%= away_stat.foul unless away_stat.nil? %></th>
            </tr>
            <tr>
                <th><%= home_stat.yellow_card unless home_stat.nil? %></th>
                <th class="centerbar">Yellow Cards</th>
                <th><%= away_stat.yellow_card unless away_stat.nil? %></th>
            </tr>
            <tr>
                <th><%= home_stat.red_card unless home_stat.nil? %></th>
                <th class="centerbar">Red Cards</th>
                <th><%= away_stat.red_card unless away_stat.nil? %></th>
            </tr>
            <tr>
                <th><%= home_stat.possession unless home_stat.nil? %></th>
                <th class="centerbar">Possessions</th>
                <th><%= away_stat.possession unless away_stat.nil? %></th>
            </tr>
            <tr>
                <th></th>
                <th><%= link_to 'Edit Match Stats', match_edit_team_stats_path(match) %></th>
                <th></th>
            </tr>
        </tbody>
    </table>
<% end %>

app/views/shared/_teamsheet.html.erb
<div class="col-xs-12 col-md-6 custyle" id="players">
  <table class="table table-striped custab">
		<thead>
			<h3 class="text-center"><%= side %> Team</h3> 
    	<tr>
        <th>Name</th>
        <th>Position</th>
        <th>Action</th>
    	</tr>
		</thead>
		<% players.each do |player| %>
      <tr>
        <td><%= link_to player.name, player %></td>
        <td><%= player.pref_position %></td>
        <td>
        	<%= render partial: 'squad_form', locals: { player: player, 
        			match: match, squad_player: find_squadplayer(match, player) } %>
        </td>
    	</tr>
		<% end %>
  </table>
</div>

app/views/shared/_userlist.html.erb
<h2 id="userlist">All users</h2>

<ul class="users">
	<% @users.each do |user| %>
		<li>
			<h4><%= user.username %></h4>
			<span><%= user.email %></span>
			<span>
				<% if current_user.admin?  %>
				|	<%= link_to "Delete", '#', method: :delete, 									data: {confirm: "You sure?" } %>
				<% end %>
			</span>	
		</li>		
	<% end %>

</ul>
<%= will_paginate @users %>