config/routes.rb
FplGuide::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'  

  resources :blogposts

  resources :teams
  resources :players do
    resources :reviews, skip: [:index, :show]
  end  
  resources :reviews, only: [:destroy]
  resources :matches do
    match 'squad_players/all/edit' => 'squad_players#edit_all', :as => :edit_squad_players, :via => :get
    match 'squad_players/all' => 'squad_players#update_all', :as => :update_squad_players, :via => :put 
    resources :squad_players, only: [:edit, :update, :create, :destroy]
    match 'team_stats/all/edit' => 'team_stats#edit_all', :as => :edit_team_stats, :via => :get 
    match 'team_stats/all' => 'team_stats#update_all', :as => :update_team_stats, :via => :put 
    resources :team_stats, skip: [:index, :show]
  end
  resources :lineups, only: [:create, :destroy]
  
  devise_for :users, skip: [:confirmations, :unlock]

  match 'home',              to: 'static_pages#home', as: :user_root, :via => :get
  match 'help',              to: 'static_pages#help'
  match 'under_development', to: 'static_pages#under_development'  
  match 'dashboard',         to: 'static_pages#dashboard'
  match 'landing',           to: 'subscribers#landing_page'
  root                       to: 'subscribers#landing_page'

  resources :users, only: [:show]
  

  resources :subscribers
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/models/squad_player.rb
class SquadPlayer < ActiveRecord::Base
  include ActiveModel::Dirty

  attr_accessible :match_id, :player_id, :starting, :lasting, :scored, :assisted,
  				  :cautioned, :sent_off, :rating, :point_gained, :gameweek
  
  belongs_to :match
  belongs_to :player

  validates :player_id, presence: true, uniqueness: true
  validates :match_id, presence: true

  after_update :increment_apps!
  after_update :increment_subs!
  after_update :increment_goals!
  after_update :increment_assists!
  after_update :increment_yellow!
  after_update :increment_red!
  after_update :increment_points!
  # after_update :increment_form!

  # def set_gameweek(match)
  #   self.gameweek = match.gameweek
  # end

  def called?(player)
    Match.squad_players.exists?(player_id: player.id)
  end

  def starter?(match, player)
    Match.squad_players.where(match_id: match.id, player_id: player.id).starting == true
  end

  def subs?(match, player)
    Match.squad_players.where(match_id: match.id, player_id: player.id).starting == false
  end

  def find_player
    Player.find_by_id(player_id)
  end


  private
  # To add stats of players

  def increment_apps! 
    if self.starting != self.starting_was
      if self.starting == true
        find_player.increment!(:appearances)
      else
        find_player.decrement!(:appearances)
      end
    end
  end

  def increment_subs! 
    if self.lasting != self.lasting_was
      if self.starting == false && self.lasting > 0
        find_player.increment!(:substitutes)
      else
        find_player.decrement!(:substitutes)
      end
    end
  end

  def increment_goals!
    if self.scored != self.scored_was
      if self.scored < self.scored_was
        find_player.decrement!(:goals, self.scored_was - self.scored)
      else
        find_player.increment!(:goals, self.scored - self.scored_was)
      end
    end
  end

  def increment_assists!
    if self.assisted != self.assisted_was
      if self.assisted < self.assisted_was
        find_player.decrement!(:assists, self.assisted_was - self.assisted)
      else
        find_player.increment!(:assists, self.assisted - self.assisted_was)
      end
    end
  end  

  def increment_yellow!
    if self.cautioned != self.cautioned_was
      if self.cautioned == true
        find_player.increment!(:yellow)
      else 
        find_player.decrement!(:yellow)
      end
    end
  end  

  def increment_red!
    if self.sent_off != self.sent_off_was
      if self.sent_off == true
        find_player.increment!(:red)
      else
        find_player.decrement!(:red)
      end
    end
  end

  def increment_points!
    if self.point_gained != self.point_gained_was
      if self.point_gained < self.point_gained_was
        find_player.decrement!(:tot_point, self.point_gained_was - self.point_gained)
      else
        find_player.increment!(:tot_point, self.point_gained - self.point_gained_was)
      end
    end
  end

  def increment_form!
    if self.rating != self.rating_was
      find_player.form_record[0...-2].concat(self.rating.to_s)
    else
      find_player.form_record.concat(self.rating.to_s)
    end
  end

end

app/controllers/squad_players_controller.rb
class SquadPlayersController < ApplicationController
	before_filter :admin_user

	def create
		@match = Match.find(params[:match_id])
		@squad_player = @match.squad_players.build(params[:squad_player])

		if @squad_player.save
			flash.now[:success] = ["Chosen for selection"]
			respond_to do |format|
				format.html { redirect_to match_path(@match) }
				# format.js
			end									
		else
			flash.now[:alert] = ["Failed to choose"]
			respond_to do |format|
				format.html { redirect_to match_path(@match) }
				# format.js
			end									
		end
	end

	def edit
		@match = Match.find(params[:match_id])
		@squad_player = SquadPlayer.find(params[:id])
	end

	def update
		@match = Match.find(params[:match_id])
		@squad_player = SquadPlayer.find(params[:id])
      
    respond_to do |format|
	      if @squad_player.update_attributes(params[:squad_player])
	        format.html { redirect_to match_path(@match), notice: 'The Squad Player was successfully updated.' }
	      else
	        format.html { render action: "edit" }
	      end
	  end
	end

	def destroy
		@match = Match.find(params[:match_id])
		@squad_player = SquadPlayer.find(params[:id])
		@squad_player.destroy
		flash.now[:info] = ["Recalled"]

		respond_to do |format|
			format.html { redirect_to match_path(@match) }
			# format.js
		end				
	end

	def edit_all
		@match = Match.find(params[:match_id])
		@squad_players = @match.squad_players.all
		# @awayplayers = @match.awayteam.players
	end

	def update_all
		@match = Match.find(params[:match_id])

	  params['squad_player'].keys.each do |id|
	    @squad_player = @match.squad_players.find(id.to_i)
	    @squad_player.update_attributes(params['squad_player'][id])
	    # Player.find_by_player_id(@squad_player.player_id).reviews.create!(rating: @squad_player.rating)
	  end

	  redirect_to match_path(@match)
	end

end

app/helpers/squad_players_helper.rb
module SquadPlayersHelper
end

app/views/squad_players/create.js.erb
$("#player_<%= @player.id %>").html("<%= escape_javascript(render partial: 'matches/recall' ) %>")

app/views/squad_players/destroy.js.erb
$("#player_<%= @squad_player.id %>").html("<%= escape_javascript(render partial: 'matches/start') %>")

app/views/squad_players/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading" id="squad">
    Edit <%= @squad_player.player.name %>'s Match Performance
  </div>
  <%= form_for([@match, @squad_player]) do |f| %>
    <table>
      <tr>
        <th class="squad">Gameweek</th>
        <th class="squad">Starting</th>
        <th class="squad">Lasting</th>
        <th class="squad">Scored</th>
        <th class="squad">Assisted</th>
        <th class="squad">Cautioned</th>
        <th class="squad">Sent-off</th>
        <th class="squad">Points</th>
        <th class="squad">Rating</th>
      </tr>
      <tr>
        <td class="num_field">
          <%= f.hidden_field :gameweek, value: set_gameweek(@match) %>
        </td>
        <td class="checkbox_field">
          <%= f.check_box :starting %>
        </td>
        <td class="num_field">
          <%= f.number_field :lasting, in: 1..90, step: 1 %>
        </td>
        <td class="num_field">
          <%= f.number_field :scored, in: 0..10, step: 1 %>
        </td>
        <td class="num_field">
          <%= f.number_field :assisted, in: 0..10, step: 1 %>
        </td>
        <td class="checkbox_field">
          <%= f.check_box :cautioned %>
        </td>
        <td class="checkbox_field">
          <%= f.check_box :sent_off %>
        </td>
        <td class="num_field">
          <%= f.number_field :point_gained, in: -10..30, step: 1 %>
        </td>
        <td class="num_field">
          <%= f.number_field :rating, in: 1..10, step: 1 %>
        </td>
      </tr>
    </table>

    <div class="actions">
      <%= f.submit "Update", class: "btn btn-success" %>
    </div>
  <% end %>
  
</div>

<%= link_to "Back", match_path(@match) %>

app/views/squad_players/edit_all.html.erb
<div class="panel panel-default">
  <div class="panel-heading" id="squad">
    Edit Squad Players
  </div>
  <%= bootstrap_form_for :squad_player, :url => match_update_squad_players_path, :html => { :method => :put } do %>
    <table>
      <tr>
        <th class="squad">Team</th>
        <th class="squad">Name</th>
        <th class="squad">Gameweek</th>
        <th class="squad">Starting</th>
        <th class="squad">Lasting</th>
        <th class="squad">Scored</th>
        <th class="squad">Assisted</th>
        <th class="squad">Cautioned</th>
        <th class="squad">Sent-off</th>
        <th class="squad">Points Gained</th>
        <th class="squad">Rating</th>
      </tr>
      <% @squad_players.each do |squad_player| %>
        <%= fields_for "squad_player[]", squad_player do |squad_player_fields| %>
      <tr>
        <td class="identifier">
          <strong>
            <%= link_to squad_player.player.team.name, team_path(squad_player.player.team)  %>
          </strong>
        </td>
        <td class="identifier">
          <strong>
            <%= link_to squad_player.player.name, player_path(squad_player.player) %>
          </strong>
        </td>
        <td class="num_field">
          <%= f.hidden_field :gameweek, value: set_gameweek(@match) %>
        </td>
        <td class="checkbox_field">
          <%= squad_player_fields.check_box :starting %>
        </td>
        <td class="num_field">
          <%= squad_player_fields.number_field :lasting, in: 1..90, step: 1 %>
        </td>
        <td class="num_field">
          <%= squad_player_fields.number_field :scored, in: 0..10, step: 1 %>
        </td>
        <td class="num_field">
          <%= squad_player_fields.number_field :assisted, in: 0..10, step: 1 %>
        </td>
        <td class="checkbox_field">
          <%= squad_player_fields.check_box :cautioned %>
        </td>
        <td class="checkbox_field">
          <%= squad_player_fields.check_box :sent_off %>
        </td>
        <td class="num_field">
          <%= squad_player_fields.number_field :point_gained, in: -10..30, step: 1 %>
        </td>        
        <td class="num_field">
          <%= squad_player_fields.number_field :rating, in: 1..10, step: 1 %>
        </td>
      </tr>
        <% end %>
      <% end %>
    </table>

    <div class="actions">
      <%= submit_tag %>
    </div>
  <% end %>
  
</div>

<%= link_to "Back", match_path(@match) %>