config/routes.rb
FplGuide::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'  

  resources :blogposts

  resources :teams
  resources :players do
    resources :reviews, skip: [:index, :show]
  end  
  resources :reviews, only: [:destroy]
  resources :matches do
    match 'squad_players/all/edit' => 'squad_players#edit_all', :as => :edit_squad_players, :via => :get
    match 'squad_players/all' => 'squad_players#update_all', :as => :update_squad_players, :via => :put 
    resources :squad_players, only: [:edit, :update, :create, :destroy]
    match 'team_stats/all/edit' => 'team_stats#edit_all', :as => :edit_team_stats, :via => :get 
    match 'team_stats/all' => 'team_stats#update_all', :as => :update_team_stats, :via => :put 
    resources :team_stats, skip: [:index, :show]
  end
  resources :lineups, only: [:create, :destroy]
  
  devise_for :users, skip: [:confirmations, :unlock]

  match 'home',              to: 'static_pages#home', as: :user_root, :via => :get
  match 'help',              to: 'static_pages#help'
  match 'under_development', to: 'static_pages#under_development'  
  match 'dashboard',         to: 'static_pages#dashboard'
  match 'landing',           to: 'subscribers#landing_page'
  root                       to: 'subscribers#landing_page'

  resources :users, only: [:show]
  

  resources :subscribers
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :name, :number, :pref_position,
  				  :playing_roles, :appearances, :substitutes, :goals,
  				  :assists, :yellow, :red, :traits, 
  				  :tot_points, :team_id, :photo

  belongs_to :team
  has_many :users, through: :lineups
  has_many :matches, through: :squad_players, foreign_key: 'player_id'
  has_many 	 :reviews

  has_attached_file :photo, :default_url => 'images/anonym_player.png',
                            :styles => { :small => "150x150>" },
                            :url  => "/assets/players/:id/:style/:basename.:extension",
                            :path => ":rails_root/public/assets/players/:id/:style/:basename.:extension"

  before_validation :clean_traits

  validates_attachment_size :photo, :less_than => 2.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/jpg', 'image/png']
	validates :name, presence: true
	validates :team_id, presence: true

  # With Squeel gem
	def self.search(query)
		where do
			(name =~ "%#{query}%") | (pref_position =~ "%#{query}%")
		end
	end


	private

  def clean_traits
    self.traits = Sanitize.fragment(self.traits, whitelist)
  end

  def whitelist
    whitelist = Sanitize::Config::RELAXED
    # whitelist[:elements].push("span")
    # whitelist[:attributes]["span"] = ["style"]
    # whitelist
  end



end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	before_filter :authenticate_user!
	before_filter :admin_user, only: [:new, :edit, :create,
																		:update, :destroy]

  def index
    @players = Player.search(params[:search]).order("appearances DESC")
  end

	def show
  	@player = Player.find(params[:id])
    @team   = @player.team_id
    @reviews = @player.reviews
	end

  def new
    @player = Player.new
    @player.team_id = params[:team_id]
  end

  def create
    @player = Player.create(params[:player])

    if @player.save
      flash[:success] = "Player added"
      redirect_to @player
    else
      render :action => "new"
    end
  end

	def edit
		@player = Player.find(params[:id])
	end

	def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end  	
	end

	def destroy
  	@player = Player.find(params[:id])
  	@player.destroy
    @team = @player.team_id

    redirect_to team_path(@team)
	end
  
end

app/views/players/_form.html.erb
<div class="container-fluid">
	<section class="container">
		<div class="container-page">
			<%= bootstrap_form_for(@player) do |f| %>

			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<section class="clear">
						<%= f.text_field :name, placeholder: "Name" %>
					</section>
				</div>
			</div>

				<div class="col-md-4">
					<div class="form-group col-lg-12">
						<%= f.file_field :photo %>
					</div>

					<div class="form-group col-lg-12">
					<%= f.number_field :team_id %>
					</div>

					<div class="form-group col-lg-12">
					<%= f.number_field :number, in: 1..100, step: 1 %>
					</div>

					<div class="form-group col-lg-12">
					<%= f.number_field :appearances, in: 0..38, step: 1%>
					</div>

					<div class="form-group col-lg-12">
					<%= f.number_field :goals, in: 0..50, step: 1 %>
					</div>

					<div class="form-group col-lg-12">
					<%= f.number_field :assists, in: 0..38, step: 1%>
					</div>

					<div class="form-group col-lg-12">
					<%= f.number_field :yellow, in: 0..25, step: 1 %>
					</div>

					<div class="form-group col-lg-12">
					<%= f.number_field :red, in: 0..10, step: 1 %>
					</div>

					<div class="form-group col-lg-12">
					<%= f.select(:pref_position, 
									["Goalkeeper","Central Defender",  "Full-back", "Wing Back",
										"Defensive Midfielder", "Central Midfielder",
										 "Attacking Midfielder", "Winger", 	
										 "Forward"]) %>
					</div>

					<div class="form-group col-lg-12">
					<%= f.select(:playing_roles,
				 						["Goalkeeper", "Sweeper Keeper", 
				 						 "Stopper", "Sweeper", "Ball-Playing Defender",
				 						 "Classic Fullback", "Overlapping Fullback",
				 						 "Deep-lying Playmaker", "Achor Man", "Box-to-Box", 
				 						 "Advanced Playmaker", "No. 10", "Classic Winger", 
				 						 "Inside Forward", "Target Man", "Poacher",
				 						 "Advanced Forward"]) %>
				 	</div>
				</div>

				<div class="col-md-8">
				  <%= f.cktext_area :traits, rows: "25" %>
 				  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
				</div>

			<% end %>
		</div>
	</section>
</div>

app/views/players/_pick.html.erb
<%= form_for(current_user.lineups.build(player_id: @player.id), remote: true) do |f| %>
	<div><%= f.hidden_field :player_id %></div>
	<%= f.submit "Pick", class: "btn btn-large btn-success" %>
<% end %>

app/views/players/_pick_form.html.erb
<% if user_signed_in? %>
	<div id="pick_form">
		<% if current_user.picked?(@player) %>
			<%= render 'unpick' %>
		<% else %>
			<%= render 'pick' %>
		<% end %>
	</div>
<% end %>

app/views/players/_player_feed.html.erb
<h3>Players</h3>

<% @team.players.each do |player| %>
<br>
<div class="container">
	<div class="row">
		<div class="col-md-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
          	<%= player.number %>. <%= player.name %>
          </h3>
          <span class="pull-right">
            <!-- Tabs -->
            <ul class="nav panel-tabs">
              <li class="active"><a href="#tab1" data-toggle="tab">Info</a></li>
              <li><a href="#tab2" data-toggle="tab">Stats</a></li>
              <li><a href="#tab3" data-toggle="tab">Traits</a></li>
            </ul>
          </span>
        </div>
        <div class="panel-body">
          <div class="tab-content">
            <div class="tab-pane active" id="tab1">
            	Position: <%= player.pref_position %> |
            	Role: <%= player.playing_roles %>
            </div>
            <div class="tab-pane" id="tab2">
            	Goals: <%= player.goals %>
              Assists: <%= player.assists %>
              Yellow Cards: <%= player.yellow %>
              Red Cards: <%= player.red %>
            </div>
            <div class="tab-pane" id="tab3">
              <%= player.traits %>
            </div>
          </div>
        </div>
      </div>
    </div>
	</div>
</div>
<% end %>

app/views/players/_player_profile.html.erb
<!-- Player picture 100x100 -->

<div class="container" style="margin-top: 20px; margin-bottom: 20px">
	<div class="row panel">
		<div class="col-md-2 col-xs-2 bg_club ">
      <%= image_tag(@player.team.photo.url(:small)) %>
		</div>
    <div class="col-md-6  col-xs-6">
      <%= image_tag(@player.photo.url(:small), class: "img-thumbnail picture hidden-xs") %>
      <%= image_tag(@player.photo.url(:small), class: "img-thumbnail visible-xs picture_mob") %>        
      <div class="header">
        <h1>
          <%= @player.number %>. <%= @player.name %> 
        </h1>
        <%= render 'pick_form' %>   
        <span><%= sanitize(@player.traits) %></span>
      </div>
    </div>
    <div class="col-md-4 col-xs-4">
      <% if current_user.admin? %>
        <%= link_to "Edit Player", edit_player_path(@player),
          class: "btn btn-primary" %>
        <%= link_to "Delete Player", player_path(@player),
          method: :delete, data: { confirm: "You sure?" },
            class: "btn btn-danger" %>        
      <% end %>
      <%= link_to "Back to the team", team_path(@team),
      class: "btn btn-info" %>                    
    </div>
  </div>   
    
	<div class="row nav" id="stats">    
    <div class="col-md-12 col-xs-12" style="margin: 0px;padding: 0px;">
      <div class="col-md-3 col-xs-3 well">
        <p class="stats">
          <%= icon('tags') %>
          <%= @player.pref_position %>, <%= @player.playing_roles %>
        </p>
      </div>
      <div class="col-md-3 col-xs-3 well">
        <p class="stats">
          <%= icon('male') %>
          <%= @player.tot_points %> in
          <%= @player.appearances %>(<%= @player.substitutes %>) appearances
        </p>
      </div>
      <div class="col-md-3 col-xs-3 well">
        <p class="stats">
          <%= icon('futbol-o') %>
          <%= @player.goals %> Goals Scored <br>   
          <%= @player.assists %> Assists
        </p>
      </div>
      <div class="col-md-3 col-xs-3 well">
        <p class="stats">
          <%= icon('flag-o') %>
          <%= @player.yellow %> Yellow card(s) <br>
          <%= @player.red %> Red card(s)
        <p>
      </div>
    </div>
  </div>
</div>

app/views/players/_search_player.html.erb
<div class="col-xs-12 col-md-4">
	<div class="panel panel-default">
	  <div class="panel-heading" id="search-player-head">

	    <span class="panel-title">
	    	<h5 id="search-player-title">Find Player</h5>
	    </span>
		
		<span>
		<%= form_tag(players_path, :method => "get", class: "navbar-form", id: "search-player-form") do %>

		    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search" %>
		  	<button class="btn" type="submit">
		   		<i class="icon-search"></i>
		  	</button>
		<% end %> 
		</span>
		
	  </div>
	  <div class="panel-body" id="search-player-body">
	    Search by name or position. Positions that are available
	    through the search are: <br>
	    <strong>Goalkeeper, Fullback, Central Defender,
	    Defensive Midfielder, Central Midfielder, Attacking Midfielder, Winger, Forward</strong>
	  </div>
	</div>
</div>

app/views/players/_unpick.html.erb
<%= form_for(current_user.lineups.find_by_player_id(@player),
			 html: { method: :delete }, remote: true) do |f| %>

	<%= f.submit "Unpick", class: "btn btn-large btn-warning" %>
<% end %>

<!-- The form for line is correct -->

app/views/players/edit.html.erb
<% provide(:title, "Edit Player") %>

<h1 class="center">Edit Player</h1>

<%= render 'form' %>

app/views/players/index.html.erb
<div class="col-xs-12 col-md-12 custyle">
  <table class="table table-striped custab">
		<thead>
			<h3 class="text-center">Search Results</h3> 
    	<tr>
        <th class="text-center">Name</th>
        <th class="text-center">Team</th>
        <th class="text-center">Position</th>
        <th class="text-center">Apps</th>
        <th class="text-center">Goals</th>
        <th class="text-center">Assists</th>
        <th class="text-center">Yellow</th>
        <th class="text-center">Red</th>
    	</tr>
		</thead>
		<% @players.each do |player| %>
			<tr>
		        <td><%= link_to player.name, player %></td>
		        <td><%= player.team.name %></td>
		        <td><%= player.pref_position %></td>
		        <td><%= player.appearances %></td>
		        <td><%= player.goals %></td>
		        <td><%= player.assists %></td>
		        <td><%= player.yellow %></td>
		        <td><%= player.red %></td>
	    	</tr>
		<% end %>
  </table>

</div>

app/views/players/new.html.erb
<% provide(:title, "New Player") %>

<h1 class="center">Add New Player</h1>

<%= render 'form' %>

app/views/players/show.html.erb
<% provide(:title, @player.name ) %>

<%= render 'player_profile' %>
<%= render '/reviews/timeline' %>