config/routes.rb
FplGuide::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'  

  resources :blogposts

  resources :teams
  resources :players do
    resources :reviews, skip: [:index, :show]
  end  
  resources :reviews, only: [:destroy]
  resources :matches do
    match 'squad_players/all/edit' => 'squad_players#edit_all', :as => :edit_squad_players, :via => :get
    match 'squad_players/all' => 'squad_players#update_all', :as => :update_squad_players, :via => :put 
    resources :squad_players, only: [:edit, :update, :create, :destroy]
    match 'team_stats/all/edit' => 'team_stats#edit_all', :as => :edit_team_stats, :via => :get 
    match 'team_stats/all' => 'team_stats#update_all', :as => :update_team_stats, :via => :put 
    resources :team_stats, skip: [:index, :show]
  end
  resources :lineups, only: [:create, :destroy]
  
  devise_for :users, skip: [:confirmations, :unlock]

  match 'home',              to: 'static_pages#home', as: :user_root, :via => :get
  match 'help',              to: 'static_pages#help'
  match 'under_development', to: 'static_pages#under_development'  
  match 'dashboard',         to: 'static_pages#dashboard'
  match 'landing',           to: 'subscribers#landing_page'
  root                       to: 'subscribers#landing_page'

  resources :users, only: [:show]
  

  resources :subscribers
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/models/match.rb
class Match < ActiveRecord::Base
  scope :gameweek, order("matches.gameweek DESC")
  scope :done, ->{ where postmatch.present? }
  attr_accessible :gameweek, :kickoff, :prematch, :postmatch,
  				  :hometeam_id, :awayteam_id

  belongs_to :hometeam, class_name: 'Team', foreign_key: 'hometeam_id'
  belongs_to :awayteam, class_name: 'Team', foreign_key: 'awayteam_id'

  has_many :squad_players
  has_many :players, through: :squad_players, foreign_key: 'match_id'
  has_many :team_stats

  before_validation :clean_pre_post_match
  validates :hometeam_id, presence: true
  validates :awayteam_id, presence: true
  validates :gameweek, presence: true

  def self.search(query)
    where { (gameweek == query) }
  end

  def self.find_all_matches(team) #find all matches involving a team, home and away
    self.where{ (hometeam_id == team.id) | (awayteam_id == team.id) }.to_a
  end

  def self.get_prev_matches(team)
    self.find_all_matches(team).map do |m| 
      if m.postmatch.present? && m.hometeam_id == team.id
        TeamStat.find_by_match_id_and_team_id(m.id, m.hometeam_id)
      elsif m.postmatch.present? && m.awayteam_id == team.id
        TeamStat.find_by_match_id_and_team_id(m.id, m.awayteam_id)
      end
    end
  end

  def self.get_next_matches(team)
    self.find_all_matches(team).map do |m| 
      if m.postmatch.empty? && m.hometeam_id == team.id
        Team.find_by_id(m.awayteam_id)
      elsif m.postmatch.empty? && m.awayteam_id == team.id
        Team.find_by_id(m.hometeam_id)   
      end
    end
  end

  def self.full_season(team) 
    self.find_all_matches(team).map do |m| 
      if m.hometeam_id == team.id || m.awayteam_id == team.id
        self.find_by_id(m.id)
      end
    end
  end

  def find_squadplayer(match, player)
    SquadPlayer.find_by_match_id_and_player_id(match.id, player.id)
  end 

  private

  def clean_pre_post_match
    self.prematch = Sanitize.fragment(self.prematch, whitelist)
    self.postmatch = Sanitize.fragment(self.postmatch, whitelist)
  end

  def whitelist
    whitelist = Sanitize::Config::RELAXED
    # whitelist[:elements].push("span")
    # whitelist[:attributes]["span"] = ["style"]
    # whitelist
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	before_filter :authenticate_user!
	before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @matches = Match.where(nil)
    @matches = @matches.gameweek(params[:gameweek]) if params[:gameweek].present?
  end

	def show
		@match = Match.find(params[:id])
    @homeplayers = @match.hometeam.players
    @awayplayers = @match.awayteam.players
    @squad_player = @match.squad_players.build
    @squad_players = @match.squad_players.all
    @home_stat = TeamStat.find_by_match_id_and_team_id(@match, @match.hometeam_id)
    @away_stat = TeamStat.find_by_match_id_and_team_id(@match, @match.awayteam_id)
	end

	def new
		@match = Match.new
	end

	def create
		@match = Match.new(params[:match])

  	respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
	end

	def edit
		@match = Match.find(params[:id])
	end

	def update
		@match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to match_path(@match), notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end		
	end

	def destroy
		@match = Match.find(params[:id])
		@match.destroy

  	respond_to do |format|
  		format.html { redirect_to user_root_path }
  		format.json { head :no_content }
  	end
	end

end

app/helpers/matches_helper.rb
module MatchesHelper

  # def called?(player)
  #   self.squad_players.exists?(player_id: player.id)
  # end

  def called?(player)
    SquadPlayer.exists?(player_id: player.id)
  end
  
  def find_squadplayer(match, player)
  	SquadPlayer.find_by_match_id_and_player_id(match.id, player.id)
  end 

  def starter?(match, player)
    Match.squad_players.where(match_id: match.id, player_id: player.id).starting = true
  end

  def find_result(match, team)
    TeamStat.find_by_match_id_and_team_id(match.id, team.id)
  end
end

app/views/matches/_backup_show.html.erb
<% provide(:title, "Match Detail") %>

<div class="row">
	<div class="col-xs-12 col-md-12">
		<h1>
			<%= link_to @match.hometeam.name, team_path(@match.hometeam) %> 
			v 
			<%= link_to @match.awayteam.name, team_path(@match.awayteam) %>
		</h1>	
	</div>
	
	<div class="col-xs-12 col-md-12">
	  <% if current_user.admin? %>
	    <%= link_to 'Edit Match', edit_match_path(@match), 
	    						  class: "btn btn-info" %>
	    <%= link_to 'Delete', match_path(@match), 
	  				method: :delete, data: { confirm: 'Are you sure?' },
	  				class: "btn btn-danger" %>
		<% end %>
	</div>

	<div class="col-xs-12 col-md-12" id="match_analysis">		
		<p><b>Match Preview</b><%= @match.prematch %></p>
	</div>

	<!-- Matchday Squad -->
	<div id="matchday_panel">
		<%= render partial: '/shared/matchday_18', locals: { players: @homeplayers, side: "Home", match: @match, squad: @squad_players, team: @match.hometeam }%>
		<%= render partial: '/shared/matchday_18', locals: { players: @awayplayers, side: "Away", match: @match, squad: @squad_players, team: @match.awayteam } %>
	</div>
	<!-- End of Matchday Squad -->


	<% if current_user.admin? %>
		<%= render partial: '/shared/teamsheet', locals: { players: @homeplayers,
				match: @match, side: "Home" } %>
		<%= render partial: '/shared/teamsheet', locals: { players: @awayplayers,
				match: @match, side: "Away" } %>
  <% end %>		

	<div class="col-xs-12 col-md-12" id="match_review">		
		<p><b>Match Review</b><%= @match.postmatch %></p>
	</div>
	
	<%= render partial: '/shared/match_review', 
							locals: { players: @squad_players, team: @match.hometeam_id} %>
	<%= render partial: '/shared/match_review', 
							locals: { players: @squad_players, team: @match.awayteam_id} %>
	<div class="col-xs-12 col-md-6-offset-3">
			<%= link_to "Edit Squad Players", match_edit_squad_players_path(@match) %>
	</div>
</div>

app/views/matches/_bench.html.erb
<%= form_for([@match, @squad_player]) do |f| %>

	<div><%= f.hidden_field :player_id, value: player.id %></div>
	<div><%= f.hidden_field :match_id, value: match.id %></div>
	
	<%= f.submit "Bench!", class: "btn btn-xs btn-info" %>
<% end %>

app/views/matches/_form.html.erb
<div class="container-fluid">
	<section class="container">
		<div class="container-page">

			<%= bootstrap_form_for(@match) do |f| %>
			<div class="row">
				<div class="col-md-4">
					<%= f.collection_radio_buttons :hometeam_id, Team.all,
						:id, :name %>
				</div>

				<div class="col-md-4">
					<%= f.collection_radio_buttons :awayteam_id, Team.all,
						:id, :name %>
				</div>

				<div class="col-md-4">
					<%= f.number_field :gameweek, in: 1..38, step: 1 %>
				</div>
			
				<div class="col-md-4">
					<%= f.datetime_select :kickoff %>
				</div>
			
				<div class="col-lg-12">
				  <%= f.label :prematch %>
				  <%= f.cktext_area :prematch, rows: "25" %>
				</div>

				<div class="col-lg-12">
				  <%= f.label :postmatch %>
				  <%= f.cktext_area :postmatch, rows: "25" %>

 				  <%= f.submit "Submit Match", class: "btn btn-large btn-primary" %>
				</div>
			</div>
			<% end %>
			<%= link_to "Back", user_root_path, class: "btn btn-large btn-info" %>
		</div>
	</section>
</div>

app/views/matches/_matches_list.html.erb
<div class="panel panel-default" id="match_panel">

	<div class="row panel-heading" id="match_heading">
		<div class="col-md-6">
			Matches |
			<% if current_user.admin? %>
				<%= link_to "Add Match", new_match_path %>
			<% end %>			
		</div>
		<div class="col-md-6">
			<%= form_tag('', method: "get", id: "gameweek-filter") do %>
				<%= select_tag :gameweek, options_for_select(@match_options), {prompt: "Gameweek" }  %>
				<%= submit_tag 'Filter', name: nil, class: "btn btn-success btn-xs" %>
			<% end %>
		</div>
	</div>
	
	<table class="match table">
	  <tr>
	    <th class="text-center">Home</th>
	    <th class="text-center">Away</th>
	    <th class="text-center">GW</th>
	    <th class="text-center">Kick-Off</th>
	  </tr>

	<% for match in @matches %>
	  <tr>
	    <td><%= link_to match.hometeam.ticker, team_path(match.hometeam) %></td>
	    <td><%= link_to match.awayteam.ticker, team_path(match.awayteam) %></td>
	    <td><%= match.gameweek %></td>
	    <td><%= match.kickoff %></td>
	    <td><%= link_to 'Details', match_path(match) %></td>
	  </tr>
	<% end %>
	</table>
</div>

app/views/matches/_recall.html.erb
<%= link_to "Recall",  match_squad_player_path(match, squad_player), 
					   method: :delete, class: "btn btn-xs btn-warning" %>

app/views/matches/_squad_form.html.erb
<div id="player_<%= player.id %>">
	<div class="row">
		<% if called?(player) %>
			<div class="col-xs-12 col-md-12">
				<%= render partial: 'recall', locals: { player: player, match: match, squad_player: squad_player }  %>
			</div>
		<% else %>
			<div class="col-xs-12 col-md-6" id="choose_player">
				<%= render partial: 'start', locals: { player: player, match: match, squad_player: squad_player } %>
			</div>
			<div class="col-xs-12 col-md-6">
				<%= render partial: 'bench', locals: { player: player, match: match, squad_player: squad_player } %>
			</div>			
		<% end %>		
	</div>
</div>

app/views/matches/_start.html.erb
<%= form_for([@match, @squad_player]) do |f| %>

	<div><%= f.hidden_field :player_id, value: player.id %></div>
	<div><%= f.hidden_field :match_id, value: match.id %></div>
	<div><%= f.hidden_field :starting, value: true %></div>
	
	<%= f.submit "Start!", class: "btn btn-xs btn-success" %>
<% end %>

app/views/matches/edit.html.erb
<% provide(:title, "Edit Match") %>
<h1>Edit Match</h1>

<%= render 'form' %>

app/views/matches/index.html.erb
<div class="panel panel-default" id="match_panel">

	<div class="panel-heading" id="match_heading">
		Matches |
		<% if current_user.admin? %>
			| <%= link_to "Add Match", new_match_path %>
		<% end %>
	</div>
	
	<table class="table">
	  <tr>
	    <th>Home</th>
	    <th>Away</th>
	    <th>GW</th>
	    <th>Kick-Off</th>
	  </tr>

	<% for match in @matches %>
	  <tr>
	    <td><%= link_to match.hometeam.name, team_path(match.hometeam) %></td>
	    <td><%= link_to match.awayteam.name, team_path(match.awayteam) %></td>
	    <td><%= match.gameweek %></td>
	    <td><%= match.kickoff %></td>
	    <td><%= link_to 'Details', match_path(match) %></td>
	  </tr>
	<% end %>
	</table>
</div>

app/views/matches/new.html.erb
<% provide(:title, 'New Match') %>

<h1>Add New Match</h1>

<%= render 'form'  %>

app/views/matches/show.html.erb
<% provide(:title, "Match Detail") %>

<div class="row">
	<div class="col-xs-12 col-md-12">
		<h1 class="text-center">
			<%= link_to @match.hometeam.name, team_path(@match.hometeam) %> 
			v 
			<%= link_to @match.awayteam.name, team_path(@match.awayteam) %>
		</h1>	
	</div>
	<div class="col-xs-12 col-md-12">
		<div class="tabbable-panel blue-heading">
			<div class="tabbable-line">
				
				<!-- Tabs -->
				<ul class="nav nav-tabs">
					<li class="active">
						<a href="#tab_default_1" data-toggle="tab">
						Prematch </a>
					</li>
					<li>
						<a href="#tab_default_2" data-toggle="tab">
						Postmatch </a>
					</li>
					<% if current_user.admin? %>
						<li>
							<a href="#tab_default_3" data-toggle="tab">
							Panel </a>
						</li>
					<% end %>
				</ul>

				<!-- Content -->
				<div class="tab-content">
					<div class="tab-pane active" id="tab_default_1">
						<div class="row">

							<div class="col-xs-12 col-md-12" id="match_analysis">		
								<h3 class="text-center">Match Preview</h3>
								<div id="pre-match">
									<%= sanitize(@match.prematch) %>
								</div>
							</div>

							<!-- Matchday Squad -->
							<% unless @squad_players.empty? %>
							<div id="matchday_panel">
								<%= render partial: '/shared/matchday_18', locals: { players: @homeplayers, side: "Home", match: @match, squad: @squad_players, team: @match.hometeam }%>
								<%= render partial: '/shared/matchday_18', locals: { players: @awayplayers, side: "Away", match: @match, squad: @squad_players, team: @match.awayteam } %>
							</div>
							<% end %>
							<!-- End of Matchday Squad -->

						</div>
					</div>

					<div class="tab-pane" id="tab_default_2">
						<div class="row">
						<% unless @match.postmatch.empty? %>
							<div class="col-xs-12 col-md-12" id="match-review">		
								<h3 class="text-center" id="review-heading">Match Review</h3>
								<div class="col-xs-12 col-md-4">
									<%=  render partial: '/shared/team_stats_table', locals: { match: @match, home_stat: @home_stat, away_stat: @away_stat, home: @match.hometeam, away: @match.awayteam } %>
								</div>
								<div class="col-xs-12 col-md-8" id="post-match">
									<%= sanitize(@match.postmatch) %>
								</div>
							</div>
							<%= render partial: '/shared/match_review', locals: { 
									match: @match, players: @squad_players, team: @match.hometeam, side: "Home"
									} %>
							<%= render partial: '/shared/match_review', locals: { 
									match: @match, players: @squad_players, team: @match.awayteam, side: "Away"
									} %>
						<% end %>
						</div>
					</div>
					
					<% if current_user.admin? %>
					<div class="tab-pane" id="tab_default_3">
						<div class="row">
							<div class="col-xs-12 col-md-12">
							 
							  <%= link_to 'Edit Match', edit_match_path(@match), 
							    						  class: "btn btn-info" %>
								<%= link_to "Edit Squad Players", match_edit_squad_players_path(@match), 
									class: "btn btn-success" %>							    						  
							  <%= link_to 'Create Stats', new_match_team_stat_path(@match) %>
							  <%= link_to 'Delete Match', match_path(@match), 
							  				method: :delete, data: { confirm: 'Are you sure?' },
							  				class: "btn btn-danger" %>
							</div>
							<% if @match.postmatch.empty? %>
								<div class="col-xs-12 col-md-12">
										<%= render partial: '/shared/teamsheet', locals: { players: @homeplayers, match: @match, side: "Home", 
											team: @match.hometeam_id  } %>
										<%= render partial: '/shared/teamsheet', locals: { players: @awayplayers,	match: @match, side: "Away", 
											team: @match.awayteam_id } %>							  				
								</div>
							<% end %>
						</div>
					</div>
					<% end %>
					
				</div>
			</div>
		</div>
	</div>
</div>	